how come this is  error free:
```py
from .user import *
from .auth import auth
from .questions import *
```
but then his throws the error: 
```py
from .auth import auth
from .user import *
from .questions import *
```
